version: "3.8"

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - 9090:9090
  catflap:
    build: .
    ports:
      - 9091:9091

volumes:
  prometheus-data:
